#include "IGraphics/Platforms/IGraphicsLinuxInput.h"

#include <cmath>
#include <iostream>
#include <string>
#include <vector>

using namespace iplug::igraphics::linux_input;

namespace {

int gFailures = 0;

void Expect(bool condition, const char* label)
{
  if (!condition)
  {
    std::cerr << "failed: " << label << '\n';
    ++gFailures;
  }
}

void ExpectNear(float actual, float expected, const char* label)
{
  Expect(std::fabs(actual - expected) < 0.0001f, label);
}

void TestCoordinateScaling()
{
  ExpectNear(DeviceToLogical(150.f, 1.f), 150.f, "100 percent device to logical");
  ExpectNear(DeviceToLogical(150.f, 1.5f), 100.f, "150 percent device to logical");
  ExpectNear(DeviceToLogical(200.f, 2.f), 100.f, "200 percent device to logical");
  ExpectNear(DeviceToLogical(100.f, 0.f), 100.f, "invalid scale fallback");
  ExpectNear(LogicalToDevice(100.f, 1.5f), 150.f, "150 percent logical to device");
}

void TestSignedXdndCoordinates()
{
  const long packed = (static_cast<long>(static_cast<uint16_t>(-120)) << 16)
                    | static_cast<uint16_t>(640);
  Expect(XdndRootX(packed) == -120, "negative Xdnd root X");
  Expect(XdndRootY(packed) == 640, "positive Xdnd root Y");
}

void TestUriListParsing()
{
  const std::string payload =
    "# generated by file manager\r\n"
    "file:///tmp/license%20one.key\r\n"
    "file://localhost/tmp/license-two.key\n"
    "file://remote.example/tmp/rejected.key\n"
    "https://example.com/not-a-file\n";
  const std::vector<std::string> paths = ParseTextUriList(payload);

  Expect(paths.size() == 2, "only local file URIs are accepted");
  if (paths.size() == 2)
  {
    Expect(paths[0] == "/tmp/license one.key", "percent-decoded file URI");
    Expect(paths[1] == "/tmp/license-two.key", "localhost file URI");
  }

  Expect(ParseTextUriList("file:///tmp/bad%00name.key\n").empty(),
         "URI containing a NUL byte is rejected");
}

} // namespace

int main()
{
  TestCoordinateScaling();
  TestSignedXdndCoordinates();
  TestUriListParsing();
  return gFailures == 0 ? 0 : 1;
}
